-- V1_create_table_event.sql

CREATE TABLE event_tb
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description TEXT,
    identifier  VARCHAR(255) NOT NULL UNIQUE,
    start_date  TIMESTAMP NOT NULL,
    end_date    TIMESTAMP NOT NULL,
    local_event VARCHAR(255) NOT NULL,
    capacity    INTEGER NOT NULL,
    organizer   VARCHAR(255),
    type        VARCHAR(255) NOT NULL
);